export const ERROR_CLIENT = "ERROR_CLIENT";
export const ERROR_SERVER = "ERROR_SERVER";
export const ERROR_SESSION = "ERROR_SESSION";

export const SUCCESS = "SUCCESS";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const ACCCESS_TOKEN = "ACCESS_TOKEN";

export const SESSION_EXPIRED = "SESSION_EXPIRED";
